# Numpy

In [1]:
lst=[1,2,3,4,5]
import numpy
numpy.array(lst)

array([1, 2, 3, 4, 5])

In [2]:
lst=[1,2,3,4,5]
import numpy as np
np.array(lst)

array([1, 2, 3, 4, 5])

In [3]:
type(np.array(lst))

numpy.ndarray

In [5]:
lst=[1,2,3,4,5]
import numpy as np
narray= np.array(lst)

In [6]:
print(narray)

[1 2 3 4 5]


In [7]:
print(type(narray))

<class 'numpy.ndarray'>


In [8]:
lst=['anirudh','gupta','python','anaconda','cobra']
numpy.array(lst)

array(['anirudh', 'gupta', 'python', 'anaconda', 'cobra'], dtype='<U8')

In [10]:
lst1=[[1,2,3],[4,5,6],[7,8,9]]
print(lst1)
print()
print(np.array(lst1))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros([2,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones([2,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
np.arange(-15,-4)

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [25]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [27]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [31]:
np.linspace(-10,-5,3)

array([-10. ,  -7.5,  -5. ])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.eye(2,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [34]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [35]:
np.random.rand(2)

array([0.56244986, 0.03064391])

In [36]:
np.random.rand(5)

array([0.76707303, 0.5737848 , 0.40472259, 0.99352481, 0.25250294])

In [40]:
np.random.randint(3)

1

In [41]:
np.random.randint(2)

0

In [48]:
np.random.randint(4)


3

# Create Rock-Paper_Scissor game

In [ ]:
#use np.random.randit(3)
#Homework

In [49]:
np.random.randint(1,100) #100 is exclusive

66

In [50]:
np.random.randint(1,100,5)

array([84, 27, 26, 88, 34])

In [51]:
np.random.randn(10)

array([-0.35250296,  1.91427788, -0.65796676,  0.44167654, -0.47778801,
        0.18222992,  0.36218003,  0.44693344,  1.49224609, -0.08105257])

In [52]:
np.random.randn(10,10)

array([[-0.37604728, -0.33652535, -1.41375091, -0.34730249, -1.04733849,
        -0.56840868,  0.80595534,  0.26510243, -0.99833856, -0.582461  ],
       [ 0.61903141,  0.46145329,  0.74700527, -1.01309733, -0.67612061,
         0.28446802,  0.12629297, -0.57710459, -0.18356019,  0.09571452],
       [-0.35964771, -1.73366907,  0.43070235,  0.99565188,  0.81422358,
        -1.29036592,  0.29699529, -1.62138325,  1.27641169, -0.07805129],
       [-0.06165193,  0.886046  ,  0.2754793 , -0.8906992 , -1.07271699,
        -1.76115749, -0.13294562,  0.19881074,  0.46842614, -1.9753148 ],
       [ 0.65358175,  0.46927562, -1.01492519,  0.2161475 , -0.33594962,
         0.03157179, -0.3433726 ,  0.16974589,  1.93320047,  0.88489263],
       [ 0.02259937, -2.8831699 ,  0.82103981, -0.23821289, -2.02868901,
         0.64067136, -2.26845983,  0.23992163, -1.07751796,  1.37150715],
       [-0.19828696, -0.22436099, -0.46611086, -0.10814355, -0.48229397,
        -1.2459451 ,  0.93431926, -0.26990353

In [53]:
narray=np.arange(0,10)
print(narray)
print(narray.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [54]:
narray=np.arange(0,10)
print(narray)
narray=narray.reshape(2,5)
print(narray)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [55]:
narray=np.arange(0,10)
print(narray)
narray=narray.reshape(3,3)
print(narray)

[0 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 10 into shape (3,3)

In [57]:
narray=np.arange(0,100)
print(narray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [58]:
print(narray.reshape(100,1).shape)

(100, 1)


In [59]:
narray=np.arange(0,100)
print(narray)
print(narray.shape)
print(narray.reshape(100,1).shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)
(100, 1)


In [60]:
narray=np.arange(0,10)
print(narray)
print()
print(narray.shape)
print()
print(narray.reshape(10,1))
print()
print(narray.reshape(10,1).shape)
print()
print(narray.reshape(2,5))
print()
print(narray.reshape(2,5).shape)
print()
print(narray.reshape(5,2))
print()
print(narray.reshape(5,2).shape)

[0 1 2 3 4 5 6 7 8 9]

(10,)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

(10, 1)

[[0 1 2 3 4]
 [5 6 7 8 9]]

(2, 5)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

(5, 2)


In [61]:
narray=np.arange(0,10)
print(narray)
print()
print(narray.reshape(2,5).reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [62]:
narray=np.arange(0,100 )
print(narray)
print()
narray=narray.reshape(10,10)
print(narray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [75]:
narray[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
narray=np.arange(0,100).reshape(10,10)
print(narray)
print()
print(narray[4,2:7])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[42 43 44 45 46]


In [77]:
narray=np.arange(0,100).reshape(10,10)
print(narray)
print()
print(narray[4,2:7])   
print()
print(narray[6:9,4:9])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[42 43 44 45 46]

[[64 65 66 67 68]
 [74 75 76 77 78]
 [84 85 86 87 88]]


In [78]:
narray[5,5]

55

In [79]:
narray[5][5]

55

In [85]:
nlst=np.random.randint(0,100,10)
nlst

array([55, 46, 68, 45, 65, 89, 93, 37, 96, 24])

In [86]:
nlst.max()

96

In [87]:
nlst.min()

24

In [88]:
nlst.argmax()

8

In [84]:
nlst.argmin()

8

In [89]:
arr=np.zeros(5)
print(arr)
print(arr.dtype)
print(arr.astype(int))

[0. 0. 0. 0. 0.]
float64
[0 0 0 0 0]


In [90]:
import numpy as np
narr_2d=np.arange(0,100).reshape(10,10)
print(narr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [91]:
narr_2d[:2,1:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [92]:
narr=np.random.randint(1,100,10)
print(narr)

[25 21 94 94 69 34 58 81 78 63]


In [93]:
narr > 50

array([False, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [94]:
narr[narr>50]

array([94, 94, 69, 58, 81, 78, 63])

In [95]:
narr[narr<50]

array([25, 21, 34])

In [97]:
narr[narr == 25]

array([25])

In [98]:
print(narr[narr > 50])
print(narr[narr < 50])
print(narr[narr >= 50])
print(narr[narr <= 50])
print(narr[narr != 50])
print(narr[narr == 50])

[94 94 69 58 81 78 63]
[25 21 34]
[94 94 69 58 81 78 63]
[25 21 34]
[25 21 94 94 69 34 58 81 78 63]
[]


In [99]:
narr=np.arange(0,10)
print(narr)
print(narr + narr)
print(narr - narr)
print(narr * narr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [100]:
narr=np.arange(0,10)
print(narr)
print(narr/narr)
#Runtiime Warning:Invalid value encountered in true_divide
#narr is containing 0 element
#So,  there is a possibility of 0/0 division which is invalid

[0 1 2 3 4 5 6 7 8 9]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\3883695119.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(narr/narr)


In [101]:
narr=np.arange(0,10)
print(narr)
print(narr**narr)

[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


In [102]:
narr=np.arange(0,10)
print(narr)
print(narr//narr)
#Runtime warning: divide by zero encountered in floor_divide

[0 1 2 3 4 5 6 7 8 9]
[0 1 1 1 1 1 1 1 1 1]


C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\4034407483.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(narr//narr)


In [103]:
narr=np.arange(0,10)
print(narr)
print(narr%narr)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]


C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\2937201104.py:3: RuntimeWarning: divide by zero encountered in remainder
  print(narr%narr)


In [104]:
0**0 #python behaviour

1

In [105]:
-1**0 #python behaviour

-1

In [107]:
narr=np.arange(0,10)
print(narr)
print(narr + narr)
print(narr - narr)
print(narr * narr)
print(narr / narr)
print(narr // narr)
print(narr % narr)
print(narr ** narr)


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[0 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\3041054937.py:6: RuntimeWarning: invalid value encountered in true_divide
  print(narr / narr)
C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\3041054937.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(narr // narr)
C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\3041054937.py:8: RuntimeWarning: divide by zero encountered in remainder
  print(narr % narr)


In [108]:
narr=np.arange(0,10)
print(narr)
print(np.sqrt(narr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [111]:
narr=np.arange(0,10)
print(narr)
print(np.sin(narr))
print(np.cos(narr))
print(np.tan(narr))
# print(np.cot(narr)) Attribute error: module 'numpy' has no attribute 'cot'
# print(np.sec(narr)) Attribute error: module 'numpy' has no attribute 'sec' 
# print(np.cosec(narr)) Attribute error: module 'numpy' has no attribute 'cosec'

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [112]:
1/np.sin(narr)

C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\1074611657.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/np.sin(narr)


array([        inf,  1.18839511,  1.09975017,  7.0861674 , -1.32134871,
       -1.04283521, -3.57889955,  1.52210106,  1.01075622,  2.42648664])

In [113]:
narr=np.arange(0,10)
print(narr)
print(np.log(narr))

[0 1 2 3 4 5 6 7 8 9]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\aniru\AppData\Local\Temp\ipykernel_12652\3579376171.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(narr))


In [114]:
narr=np.random.randint(1,100,10)
print(narr)
print(np.log(narr))

[12  5 69 30 26 98 14 29 96 46]
[2.48490665 1.60943791 4.2341065  3.40119738 3.25809654 4.58496748
 2.63905733 3.36729583 4.56434819 3.8286414 ]


In [115]:
a=5/5.5
b=5*5.5
print(a//b) #tricky question

0.0
